name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      #Naming convention?  Use '@'? '-'?
      compilers: [gcc@8.3.0]
      #matrix:
      #build_type: [Debug, Release]

    name: "${{ compilers }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install Environment ${{ compilers }}
        #Does this need a .yml at the end?
        run: spack env install mpact-dev-${{ compilers }}

        #- name: Configure
        #  run: |
        #    cmake -S . -B build \
        #          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

        #- name: Build
        #  run: make -C build

        #- name: Run tests
        #  run: CTEST_OUTPUT_ON_FAILURE=ON make -C build test
